def Help():

    while True:

        print("""
==============================
          HATTORI HELP
==============================

1. General Help
2. Tools Help
3. Commands Help
4. Output Manager Help

B. Back
E. Exit
""")

        choice = input("Enter your option: ")

        if choice == "1":

            print("""
==============================
        GENERAL HELP
==============================

Hattori is a multi-tool program that
provides different utilities for
hashing, networking, encoding,
OSINT and other tasks.

The main page provides access to:

M / Menu
    Open the Hattori tools menu.

O / Output
    Open Output Manager.

H / Help
    Open this help section.

E / Exit
    Exit Hattori.
""")

            input("\nPress Enter to continue...")

        elif choice == "2":

            print("""
==============================
          TOOLS HELP
==============================

==============================
TOOLS HELP
==========

1. Hash
   Generate cryptographic hashes
   from text using supported
   hashing algorithms.

2. IP Finder
   Find your local IP address or
   public IP address.

3. Password Generator
   Generate random passwords with
   a selectable length and different
   character types.

4. Base64
   Encode text into Base64 or
   decode Base64 data back into
   text.

5. DNS Lookup
   Resolve a domain name and
   display its hostname, aliases
   and IP addresses.

6. Ping
   Check whether a host is
   reachable and measure the
   connection response time.

7. Port Scanner
   Scan a selected range of TCP
   ports on a host and identify
   open ports and their services.

8. Banner Grabber
   Connect to a service and
   retrieve its available banner
   information.

9. WHOIS Lookup
   Retrieve WHOIS registration
   information for a domain,
   including registrar, creation
   date, expiration date,
   updated date, status and
   name servers.

10. IP Geolocation
    Find geographical and network
    information associated with an
    IP address, including country,
    region, city, ZIP code,
    coordinates, timezone, ISP,
    organization and AS information.

    You can also enter ME to
    automatically use your public IP.

11. HTTP Headers Analyzer
    Connect to a URL and retrieve
    and display the HTTP response
    headers returned by the server.

""")

            input("\nPress Enter to continue...")

        elif choice == "3":

            print("""
==============================
        COMMANDS HELP
==============================

MAIN PAGE

M / Menu
    Open the tools menu.

O / Output
    Open Output Manager.

H / Help
    Open Help.

E / Exit
    Exit Hattori.


INSIDE TOOLS

B / Back
    Return to the previous menu.

E / Exit
    Exit Hattori.


IMPORTANT

Commands are generally not
case-sensitive.

For example:

M
m
Menu
menu

can all be used to open Menu.
""")

            input("\nPress Enter to continue...")

        elif choice == "4":

            print("""
==============================
      OUTPUT MANAGER HELP
==============================

Output Manager is the central
system for managing results
generated by Hattori tools.

1. View saved outputs
    View previously saved results.

2. Search outputs
    Search through saved results.

3. Delete output
    Delete a saved result.

4. Rename output
    Rename a saved result.

5. Export output
    Copy a saved result to another
    location.

Saved outputs are stored inside
the outputs folder.

The Output Manager is available
from the main Hattori page using:

O / Output
""")

            input("\nPress Enter to continue...")

        elif choice.lower() == "b":

            return "back"

        elif choice.lower() == "e" or choice.lower() == "exit":

            return "exit"

        else:

            print("\nInvalid option!")
